menubar: false
branding: false
force_br_newlines : true
force_p_newlines : false
forced_root_block : ''
invalid_elements: "div"
toolbar:
  - bold italic underline bullist numlist
plugins:
  - link
  - textcolor
  - lists
  - placeholder
